### ISSUE TITLE
HostDynamicWorkload.updateVmsProcessing() throws NullPointerException

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Cloudslab/cloudsim#20]
```
What steps will reproduce the problem?
1. Use r100 trunk CloudSim
2. Run DVFS.java in power examples
3. Use VmSchedulerSpaceShared instead of VmSchedulerTimeShared (default) and 
recompile, run again

What is the expected output? What do you see instead?

New resource usage for the time frame starting at 5.00:

5.00: [Host #0] Total allocated MIPS for VM #0 (Host #0) is 222.70, was requeste
d 222.70 out of total 250.00 (89.08%)
java.lang.NullPointerException
        at org.cloudbus.cloudsim.HostDynamicWorkload.updateVmsProcessing(Unknown
 Source)
        at org.cloudbus.cloudsim.power.PowerDatacenter.updateCloudetProcessingWi
thoutSchedulingFutureEventsForce(Unknown Source)
        at org.cloudbus.cloudsim.power.PowerDatacenter.updateCloudletProcessing(
Unknown Source)
        at org.cloudbus.cloudsim.Datacenter.processEvent(Unknown Source)
        at org.cloudbus.cloudsim.core.SimEntity.run(Unknown Source)
        at org.cloudbus.cloudsim.core.CloudSim.runClockTick(Unknown Source)
        at org.cloudbus.cloudsim.core.CloudSim.run(Unknown Source)
        at org.cloudbus.cloudsim.core.CloudSim.startSimulation(Unknown Source)
        at DVFS.main(DVFS.java:84)
Unwanted errors happen
DVFS example finished!

What version of the product are you using? On what operating system?
r100 trunk CloudSim
Windows XP SP3
JDK 1.6.0_26

Please provide any additional information below.

I traced the code. In HostDynamicWorkload.updateVmsProcessing() method:

List<Pe> pes = getVmScheduler().getPesAllocatedForVM(vm);

may return null in VmSchedulerSpaceShared. 
(VmSchedulerSpaceShared.getPesAllocatedForVM)
Thus when run this line:

for (Pe pe : pes) {

It will throw a NullPointerException.

I don't know why VmSchedulerSpaceShared.getPesAllocatedForVM returns null, but 
we can prevent it by adding an assertion before for().

if (pes != null) {
   for () ...
}
```

Original issue reported on code.google.com by `scrib...@gmail.com` on 26 Nov 2011 at 6:07

Attachments:
- [cloudsim-latest-trunk.jar](https://storage.googleapis.com/google-code-attachments/cloudsim/issue-20/comment-0/cloudsim-latest-trunk.jar)
- [DVFS.java](https://storage.googleapis.com/google-code-attachments/cloudsim/issue-20/comment-0/DVFS.java)

**Comment by Olverant** [comment]
I'm having the same problem commented previously about pes returns null in the class HostDynamicWorkload.java.

"for (Pe pe : pes) {"

This problem occurs when I use "VmSchedulerSpaceShared", but when I use "VmSchedulerTimeShared"
and time shared over subscription it works fine. Any help?
